"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getViewer } from "@/lib/auth/get-viewer";
import { postTeamsCard } from "@/lib/teams/post-card";
import { testCard } from "@/lib/teams/cards";

export interface SimpleActionState {
  error: string | null;
  success: boolean;
}

export interface TeamsConnectionFields {
  team_name: string | null;
  channel_name: string | null;
  outbound_webhook_url: string | null;
  /** Teams generates this itself when the Outgoing Webhook is created and
   * shows it once in the setup dialog -- pasted here, not generated by
   * Objectra. Undefined leaves the stored secret untouched (so re-saving
   * the other fields doesn't require re-pasting it every time). */
  inbound_hmac_secret?: string;
  notify_created: boolean;
  notify_status: boolean;
  notify_sla: boolean;
  is_active: boolean;
}

export async function upsertTeamsConnection(projectId: string, fields: TeamsConnectionFields): Promise<SimpleActionState> {
  const viewer = await getViewer();
  if (!viewer) redirect("/sign-in");

  const supabase = await createClient();
  const { error } = await supabase
    .from("teams_connections")
    .upsert({ project_id: projectId, ...fields }, { onConflict: "project_id" });

  if (error) return { error: error.message, success: false };
  revalidatePath("/settings");
  return { error: null, success: true };
}

/** "Send test card" -- mirrors sendTestTicketEmail's shape (notify-ticket.ts):
 * builds a fixture and posts it directly, since there's no real ticket event
 * to re-run. */
export async function sendTestTeamsCard(projectId: string): Promise<SimpleActionState> {
  const viewer = await getViewer();
  if (!viewer) redirect("/sign-in");

  const result = await postTeamsCard(projectId, testCard(), "test_card");
  if (!result.ok) return { error: result.error ?? "Couldn't reach the configured webhook.", success: false };
  return { error: null, success: true };
}
